version: "3.2"

services:
  dev:
    container_name: celer-network
    image: parity/rust-builder:latest
    working_dir: /var/www/celer-network
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/celer-network/.cargo
    volumes:
      - .:/var/www/celer-network
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/celer-network --dev --ws-external"
